### PR TITLE
fixed undefined option for Mac OS X

### PR DESCRIPTION
**Pull request by malter**

### CODE REVIEW

**Comment by goldhoorn** [comment]
Seems macos does not support "no access time" change setting, therefore ack for merge

**Comment by goldhoorn** [comment]
@doudou ping

**Comment by doudou** [comment]
noatime is linux-specific and there's zero reason to use it in the first place. Just remove it.

**Comment by goldhoorn** [comment]
@malter: Please update the PR regarding sylvains last comment

**Pull request merged**
